name: CI

on:
  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      BUILD_ENV: local
    secrets: inherit

  lint:
    needs: [setup]
    uses: ./.github/workflows/lint.yml
    with:
      BUILD_ENV: local
    secrets: inherit

  unit-tests:
    needs: [lint]
    uses: ./.github/workflows/unit-tests.yml
    with:
      BUILD_ENV: local
    secrets: inherit

  build-sso:
    needs: [unit-tests]
    uses: ./.github/workflows/projects.yml
    with:
      ENVIRONMENT: SSO STG
      BUILD_ENV: local
      PATH: dist
      PROJECT: sso
      COMMAND: build
      FIREBASE_PROJECT_ID: clube-do-afiliado-homolog
      SSO_URL:  ${{ vars.STG_SSO_URL }}
      ADMIN_URL: ${{ vars.STG_ADMIN_URL }}
      STORE_URL:  ${{ vars.STG_STORE_URL }}
      BACKOFFICE_URL:  ${{ vars.STG_BACKOFFICE_URL }}
    secrets: 
      FIREBASE_API_KEY: ${{ secrets.STG_FIREBASE_API_KEY }}
      FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.STG_FIREBASE_MESSAGING_SENDER_ID }}
